version: '3'
services:
  node-app:
   container_name: express-node-app
   image: mahmoud899/mernstack
   build: .
   volumes:
   - ./src:/app/src:ro
   ports:
   - "4000:4000"
   env_file:
   - ./.env
   depends_on:
   - mongo
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  nginx:
    image: nginx:stable-alpine
    ports:
    - "81:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - node-app

  